defaults: &defaults
  docker:
    - image: buildpack-deps:xenial
      environment:
        LANG: C.UTF-8
        EMSCRIPTEN_ALLOW_NEWER_PYTHON: 1
  working_directory: ~/

test-defaults: &test-defaults
  <<: *defaults
  steps:
    - checkout:
        path: emscripten/
    - attach_workspace:
        # Must be absolute path or relative path from working_directory
        at: ~/

    - run: |
        apt-get update
        apt-get install -y python3 python3-pip cmake build-essential openjdk-9-jre-headless $TEST_DEPENDENCY
        pip3 install --upgrade pip
        pip3 install lit
        EMCC_CORES=4 python3 emscripten/tests/runner.py $TEST_TARGET

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout:
          path: emscripten/
      - run: |
          apt-get update
          apt-get install -y python3 cmake
          wget https://github.com/juj/emsdk/archive/master.tar.gz
          tar -xf master.tar.gz
          pushd emsdk-master
          ./emsdk update-tags
          ./emsdk install latest
          ./emsdk activate latest
          popd
          echo EMSCRIPTEN_ROOT="'~/emscripten/'" >> .emscripten
          echo BINARYEN_ROOT="''" >> .emscripten
          EMCC_CORES=4 python3 emscripten/embuilder.py build ALL
          python3 emscripten/tests/runner.py test_hello_world
          mkdir tmp-firefox-profile/
          echo 'user_pref("javascript.options.shared_memory", true);' >> tmp-firefox-profile/user.js

      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: ~/
          # Must be relative path from root
          paths:
            - emsdk-master/
            - .emscripten_cache/
            - .emscripten_ports/
            - .emscripten
            - tmp-firefox-profile/

  test-sanity:
    <<: *test-defaults
    environment:
      - TEST_TARGET=sanity

workflows:
  version: 2

  build-test:
    jobs:
      - build
      - test-sanity:
          requires:
            - build

